### ISSUE TITLE
Make the ID field in player_events be generic

### ISSUE THREAD

**Issue by lilserf** [Society-for-Internet-Blaseball-Research/prophesizer#14]
Might be a player, might be a team - context-dependent

**Comment by ifhbiff** [comment]
I would piggyback on this and see that the table should also be changed to outcome_events, outcomes, or another name that more easily distinguishes it from game_events and not just player specific.

**Comment by ifhbiff** [comment]
New thought/name suggestion: modification_events.  See "Schema Rework" , 3rd message.
