### ISSUE TITLE
Batter change not handled cleanly; results ascribed to previous batter, game_event_id 213714

### ISSUE THREAD

**Issue by ifhbiff** [Society-for-Internet-Blaseball-Research/prophesizer#15]
Example:
game_event_id 213714
event_text: {"Don Mitchell batting for the Lovers.","Ball. 1-0","Sigmund Castillo hits a solo home run!"}

The event is currently ascribed to Don Mitchell.   The previous and subsequent game_events are correct; it just appears to be a data loss between the end of Mitchell's at bat and the start of Castillo's.

EDIT: Next game_event indicates Mitchell was out, reason unknown.

**Comment by lilserf** [comment]
If possible, can you specify the season / day and game_id?
My game_event_id on my copy of the DB might very well be different at this point

**Comment by ifhbiff** [comment]
Season 4, Day 71, bottom 2.
