### ISSUE TITLE
Incinerations not tracked

### ISSUE THREAD

**Issue by ifhbiff** [Society-for-Internet-Blaseball-Research/prophesizer#31]
The following 18 players appear to have been incinerated, but do not have the deceased flag set to true, or an equivalent record on player_events:

player_name	player_id
Jessi Wise	57448b62-f952-40e2-820c-48d8afe0f64d
Aldon Anthony	4bda6584-6c21-4185-8895-47d07e8ad0c0
Scrap Murphy	40db1b0b-6d04-4851-adab-dd6320ad2ed9
Dickerson Greatness	3afb30c1-1b12-466a-968a-5a9a21458c7f
Matheo Carpenter	ab9eb213-0917-4374-a259-458295045021
Alexandria Dracaena	262c49c6-8301-487d-8356-747023fa46a9
Theodore Passon	64b055d1-b691-4e0c-8583-fc08ba663846
Lars Mendoza	76c4853b-7fbc-4688-8cda-c5b8de1724e4
Derrick Krueger	bd9d1d6e-7822-4ad9-bac4-89b8afd8a630
Cedric Gonzalez	6fc3689f-bb7d-4382-98a2-cf6ddc76909d
Caligula Lotus	f7715b05-ee69-43e5-a0e5-8e3d34270c82
Famous Oconnor	bca38809-81de-42ff-94e3-1c0ebfb1e797
Sosa Elftower	c86b5add-6c9a-40e0-aa43-e4fd7dd4f2c7
Hurley Pacheco	b86237bb-ade6-4b1d-9199-a3cc354118d9
Trevino Merritt	70a458ed-25ca-4ff8-97fc-21cbf58f2c2a
Shaquille Torres	495a6bdc-174d-4ad6-8d51-9ee88b1c2e4a
Tiana Cash	3d4545ed-6217-4d7a-9c4a-209265eb6404
Zi Delacruz	c83a13f6-ee66-4b1c-9747-faa67395a6f1

Making some attempts to get the details for them, but will try not to fall too far down the rabbit hole.  At the minimum, I believe the Wiki page for Incinerations should have the full list.

**Comment by ifhbiff** [comment]
UPDATE: It appears to be the 17 players incinerated in Season 2 (before our game_event data), plus Caligula Lotus, the most recent player incinerated (Season 6, Day 31).  Gonna do a quick check of the text for that last one.

**Comment by ifhbiff** [comment]
game_id: e0ac1b4e-c5d7-4534-86a6-286fbd103850
Top of the 1st

{"Sigmund Castillo batting for the Lovers.","Rogue Umpire incinerated Flowers hitter Caligula Lotus! Replaced by Hiroto Cerna","Don Mitchell  scores on the sacrifice."}   It is on player_events, but listed as player_id = 'UNKNOWN'

**Comment by lilserf** [comment]
Looked at the Caligula Lotus case - they're incinerated in the top of the 1st before Cauldron has seen them bat or pitch, so it doesn't have a valid ID for them in its map.
We should either delay filling in the player IDs until we emit the game, or actually query the datablase itself while processing in order to reverse-lookup a player

**Comment by lilserf** [comment]
We also need to have incinerations break the at bat like steals do, right?

**Comment by lilserf** [comment]
Fixed Caligula Lotus
