### ISSUE TITLE
Parsing error fix credits wrong batter

### ISSUE THREAD

**Issue by ifhbiff** [Society-for-Internet-Blaseball-Research/prophesizer#32]
df236cb4-3537-4d02-a7ce-544febad8acc , top of the 9th, event index 67 for the game ... the text says that Blood Hamburger hit a triple, but it appears the attempt to manually fix this gave credit to Grey Alvarado during the Shoe Thief half of inning, when Alvardo is actually in the Breath Mint lineup.  Looks like this manual fix just found the batter of the other lineup.

**Comment by lilserf** [comment]
This is Season 4 Day 69, Shoe Thieves vs Mints
