### ISSUE TITLE
pitcher_id's change incorrectly on final play of half-inning

### ISSUE THREAD

**Issue by no-space** [Society-for-Internet-Blaseball-Research/prophesizer#5]
Example:
Game id 993c5877-7c05-4eb8-9fd0-ec8dda2d91d7
Event id 2048504, routine play: pitcher_id b6aa8ce8-2587-4627-83c1-2a48d44afaee, pitcher_team_id 7966eb04-efcc-499b-8f03-d13916330531
Event id 2048505, double play to end the inning: pitcher_id changes to 73265ee3-bb35-40d1-b696-1f241a6f5966, pitcher_team_id remains the same
Event id 2048506, start of next inning: pitcher_id remains the same, pitcher_team_id switches to b72f3061-f573-40d7-832a-5ad475bd7909

**Comment by lilserf** [comment]
Fixed!
