### ISSUE TITLE
Schema Rework

### ISSUE THREAD

**Issue by lilserf** [Society-for-Internet-Blaseball-Research/prophesizer#8]
1) Move the "home" of the schema file to prophesizer somewhere
2) Generate the schema using pg_dump rather than painstakingly hand-writing it to match what has been done in pgAdmin etc
3) Add some kind of script for doing a standardized schema dump. For instance, the most recent one I did was:
```pg_dump -U postgres -c -O -s blaseball > schema.sql```
Hm, username and database will need to be params somehow.
4) Document these processes

**Comment by ifhbiff** [comment]
Created first fork and then pull request for Prophesizer, which is the same code but included two pg_dump genereated .sql files.  The commands used to generate them were:

pg_dump -d blaseball -U postgres -c -O -n 'taxa' > schema_data.sql
pg_dump -d blaseball -U postgres -c -O -s -n '(public|raw|xref)' > schema_clean.sql

Will work towards putting a small Python script in the /db folder that runs/tracks these.

**Comment by ifhbiff** [comment]
**PUBLIC TABLE STRUCTURE CHANGE PROPOSALS (First Batch):**

ADD games.home_score_start
ADD games.away_score_start
games.day to games.gameday
game_events.id to game_events.game_event_id
game_events.day to game_events.gameday
game_events_base_runners.id to game_events_base_runners.game_events_base_runner_id
imported_logs.id to imported_logs.imported_log_id
players.id to players.player_db_id
players.coffee to players.coffee_id
players.blood to players.blood_id
ADD players.player_modification_event_id ?
player_events to player_modification_events
player_events.id to player_modification_events.player_modification_event_id
player_events.event_type to player_modification_events.modification_event
teams.id to teams.team_db_id
ADD teams.league_id
ADD teams.division_id
time_map.day to time_map.gameday
